### ISSUE TITLE
Repository description

### ISSUE THREAD

**Issue by yungyuc** [cesehub/cesehub#1]
The repository is for developing the web site for the CESE method at [cesehub.org](http://cesehub.org).  The current repository description is:

> cesehub hosts information to access the CESE method. It includes the introduction of the CESE method, the related publications and the programs to demo the CESE method.

It makes more sense to write a more explicit message:

> This repository is for [The CESE Hub](http://cesehub.org).  The CESE Hub is a web site to introduce and collect information for [the space-time conservation element and solution element (CESE) method](http://www.grc.nasa.gov/WWW/microbus/).

**Comment by tai271828** [comment]
sounds great idea. +1

**Comment by tai271828** [comment]
the project description of github seems not to support markdown (yet). I provide the url info in README.md.

**Comment by yungyuc** [comment]
I have a new idea.  How about make the description even more concise?  Like

> Web site to collect relevant information about the CESE method

**Comment by tai271828** [comment]
How about this?

Use

> Web site to collect relevant information about the CESE method

in the project description and

Use

> This repository is for The CESE Hub. The CESE Hub is a web site to introduce and collect information for the space-time conservation element and solution element (CESE) method.

in the README first head.
