### ISSUE TITLE
Page/post title line doesn't wrap correctly

### ISSUE THREAD

**Issue by yungyuc** [cesehub/cesehub#13]
When a title line is long enough (and the page width is narrow enough), you'll see overlapped text:

![screen shot 2016-05-29 at 8 19 56 am](https://cloud.githubusercontent.com/assets/399122/15630637/3c4379a6-2576-11e6-968a-2fac9c0d0402.png)

**Comment by tai271828** [comment]
This bug is confirmed. It could be reproduced by sizing the browser window. Please try to shrink the width of the window and we could get this issue.

**Comment by yungyuc** [comment]
That's what I did (sizing down the window) to see this problem.

**Comment by tai271828** [comment]
The issue is fixed by removing the fixed line height. Thanks for the feedback.
