### ISSUE TITLE
feedback about the CESEHUB's intstruction

### ISSUE THREAD

**Issue by yuhow** [cesehub/cesehub#22]
I tried to follow the CESEHUB's README file to test its instruction step by step. Basically, everything is quite clear and very easy-understanding. But I still have some suggestion about this instruction. You can find some feedback from my side in the following message:
1. After I entered the following command to merge the gh-page with the dev one:
   git merge dev

Nothing came out like a prompt from my default editor. It only showed some message on my console like: 
Updating 34e1d3a..059f38c
Fast-forward
 codes/codes.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

I suggest maybe the description "Your terminal will prompt for the commit message with default editor. Save it to confirm this merge." can be modified. 
1. I think it will be great to add a short paragraph to explain each "merge" and "push" really did. So that a freshman can have a clear picture of what those commands mean and what you want them to learn. 

Hope these suggestion are helpful :D

**Comment by yungyuc** [comment]
@yuhow could you please make a pull request containing your suggestion?

**Comment by yuhow** [comment]
@yungyuc no problem.

**Comment by tai271828** [comment]
closed this issue because PR https://github.com/cesehub/cesehub/pull/24 was merged.
