### ISSUE TITLE
Cover gif is wider than text and it looks bad

### ISSUE THREAD

**Issue by yungyuc** [cesehub/cesehub#4]
Is there a way to make it the same wide as the text?

![screen shot 2016-05-25 at 7 38 04 pm](https://cloud.githubusercontent.com/assets/399122/15538689/4fd34762-22b0-11e6-9298-08a1c2525fa4.png)

**Comment by tai271828** [comment]
I think this doable. Let me try to do it.

**Comment by tai271828** [comment]
done. thanks for your feedback.

**Comment by yungyuc** [comment]
Looks wonderful.  Thanks a lot!
