### ISSUE TITLE
Does jekyll support mathjax?

### ISSUE THREAD

**Issue by yungyuc** [cesehub/cesehub#5]
It will be very useful to write LaTeX in web page and render it to mathjax.

**Comment by tai271828** [comment]
I have no idea but it is a good idea which is worthy of our investigation. I will survey this solution is doable or not.

**Comment by yungyuc** [comment]
kramdown seems to support mathjax, but needs some configuration.  I haven't investigate it yet.

**Comment by tai271828** [comment]
kramdown supports mathjax. Follow the following steps to start to support mathjax in the source code.
- add the following script statement in into the head of _layouts/default.html

```
<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
```
- now writing latex in the post supported by kramdown

Please refer to this fork commit as an example:
https://github.com/tai271828/cesehub/commit/cc93edaed1ba77fdfeedb8fd017b897bc7313291

Refer to the document of mathjax:
http://docs.mathjax.org/en/latest/start.html
