### ISSUE TITLE
port http://www.grc.nasa.gov/WWW/microbus/ to a better framework.

### ISSUE THREAD

**Issue by tai271828** [cesehub/cesehub#6]
[This website](http://www.grc.nasa.gov/WWW/microbus/) uses native html framework and it provides bad user experience. The first step to build cesehub is to port the contents of [this website](http://www.grc.nasa.gov/WWW/microbus/) to a website with better framework.
### Action Items
- [ ] contact Dr. Chang
- [x] CESE - Home title should be CESE Hub
- [ ] fine tune the contents and layout.
#### fine tune the contents
- [ ] codes
- [ ] NASA WEB PRIVACY POLICY AND IMPORTANT NOTICES
- [ ] url for some of the publications

**Comment by yungyuc** [comment]
I probably should contact Dr. Chang to learn what contents he'd like us to move to cesehub.  For now cesehub has a basic look & feel and starting to discuss contents makes sense.

**Comment by yungyuc** [comment]
I suggest we fine-tune the pages before migrating the contents.  For example, cesehub.org still shows `<title>CESE - Home</title>`, which isn't consistent to the name "CESE Hub".

**Comment by tai271828** [comment]
The web site is getting to be ported.
Many pages are ported to cesehub.org
I wish Dr. Chang will see the latest cesehub.org

The remaining items:
- [ ] codes
- [ ] NASA WEB PRIVACY POLICY AND IMPORTANT NOTICES
- [ ] url for some of the publications

These items will be tracked in the 1st comment.

**Comment by yungyuc** [comment]
@tai271828 I am not sure we should rip all the contents from http://www.grc.nasa.gov/WWW/microbus/ .  They should be copyrighted by the site maintainer.  It should be fine to take the microbus front page as a placeholder for this new site.  But it's a placeholder and we should author original contents.

And this site isn't suitable for any "NASA" information.  I suggest to not port the "NASA WEB PRIVACY POLICY AND IMPORTANT NOTICES".

Perhaps we should focus on organizing the contents.  Could you try to come up with a different way of sectioning?  I mean the items in the left-side navigation column.  How about making the following sections?
1. Publications.
2. Codes.
3. Related links.

**Comment by tai271828** [comment]
Thanks for the reminder. Let me remove the privacy policy first.

Different ways to sort the sections are welcome.

**Comment by tai271828** [comment]
In accordance with the copyright concern, I suggest that we could stop this issue here. The current contents are enough for us to demo the layout to Dr. Chang.
